server:
  keepaliveperiodsecond: 0
  listenaddr: ""
  port: 8080

  ssl:
    enable: false
    redirecttohttps: true
    listenaddr: ""
    port: 443
    certfile:
    keyfile:
    letsencrypt:
      enable: false
      accepttos: true
      email: "stefanwellhoner@gmail.com"
      cache: "/data/certs"
      hosts:
        - "wellhoner.com"
        - "wellhoner.co.za"
      renewbefore: 30

database:
  host: "localhost"
  port: 5432
  user: "taskforge_user"
  password: vUFl8tw2s9i8kIyw
  database: "taskforge"
  sslmode: "disable"
  maxRetries: 10
  retryInterval: 10

secrets:
  jwt: k+bQu6EgGx30l/VNhRfYwgkWxo5Ce4x8H2/YvoHDHxYJoUzB2gKK3h8oYIP7oW3soWzxYme2Dt2xXyTn0iDvvA==

passstrength: 10
