version: '3.8'

services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    command: ["./wait-for-it.sh", "db:5432", "--", "./taskforge"]

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taskforge_user
      POSTGRES_PASSWORD: vUFl8tw2s9i8kIyw
      POSTGRES_DB: taskforge
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
    driver: local
