name: build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v2
              with:
                  go-version: 1.21.x
            - uses: actions/cache@v2
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-
            - uses: actions/checkout@v2
            - run: go mod download

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - run: make test
